### ISSUE TITLE
Two-dimensional indicatrices

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#31] opened 2021-07-08 09:25 UTC
I do not see the possibility of calculating two-dimensional indicatrices (-store_scat_grid and -phi_integr). And here you will have to think about how to display the indicatrix correctly. Or a graph of a function of two variables, i.e. surface, or sections - here the choice of the column for X, which is now on the chart, may come in handy (for a one-dimensional indicatrix it is almost unnecessary). But then you will need one more control (drop-down list) to select the value of a different angle. Although this list will be long - you can think about the possibility of writing it by hand, and then the GUI itself will round up to the nearest value that is in the file.

**Comment by myurkin** [comment] 2021-07-08 11:27
I guess, this can be considered a duplicate of #20 (no need to divide the latter into two).

**Closed as completed by myurkin** 2021-07-08 11:27 UTC
Labels: duplicate
